# https://zhuanlan.zhihu.com/p/471484611

# CUDA基础镜像
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu18.04

# 这个版本的问题是cuda11.8只有pytorch2.0级以上的配套，但是apex又不能支持，apex只能支持道pytorch1.13

# 安装基础包
RUN apt update && \
    apt install -y \
        wget build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev \
        libreadline-dev libffi-dev libsqlite3-dev libbz2-dev liblzma-dev && \
        apt-get install -y liblzma-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /temp

# 下载python # 编译&安装python
RUN wget https://www.python.org/ftp/python/3.8.7/Python-3.8.7.tgz && \
    tar -xvf Python-3.8.7.tgz && \
    cd Python-3.8.7 && \
    ./configure --enable-optimizations && \
    make && \
    make install

WORKDIR /workspace

RUN rm -r /temp && \
    ln -s /usr/local/bin/python3 /usr/local/bin/python && \
    ln -s /usr/local/bin/pip3 /usr/local/bin/pip && \
    set -x; buildDeps='gcc libc6-dev make wget vim gcc g++ libxml2 libstdc++6 pciutils software-properties-common git python3.8-dev cmake mpich' \
    && apt-get update \
    && apt-get install -y $buildDeps \
    && mkdir -p /.pip \
    && cd /.pip \
    && echo "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple\n[install]trusted-host = https://pypi.tuna.tsinghua.edu.cn" > pip.config



##执行
#docker build -t cnstark/pytorch:1.13.1-py3.8.10-cuda11.8.0-ubuntu18.04 -f dockerfile-11.8.0-cudnn8-devel-ubuntu18.04.txt .
#amd00@MZ32-00:~/yk_repo/Megatron-LM/tag_23.06$ sudo docker images
#REPOSITORY                    TAG                                      IMAGE ID       CREATED         SIZE
#cnstark/pytorch               1.13.1-py3.8.10-cuda11.8.0-ubuntu20.04   656c5f3aa0a7   5 minutes ago   9.82GB

#启动方式
#为什么加 --entrypoint=/bin/bash  https://stackoverflow.com/questions/38992850/trying-to-run-cloudera-image-in-docker
# amd00@MZ32-00:~/yk_repo/Meg
# sudo docker run -it --entrypoint=/bin/bash -v /home/amd00:/workspace -v /data:/share --name meg_codeparrot --gpus=all --shm-size="100G" cnstark/pytorch:1.13.1-py3.8.10-cuda11.8.0-ubuntu18.04

# root@52084a8e6666:/share/yk_repo/Megatron-LM/tag_23.06# pip install torch -i https://mirror.baidu.com/pypi/simple/


# amd00@MZ32-00:~/yk_repo/Megatron-DeepSpeed$ sudo docker start 656c5f3aa0a7  已经创建，
# 656c5f3aa0a7

# /usr/local/bin/python3.8 -m pip install --upgrade pip

# pip install numpy six regex wheel -i https://mirror.baidu.com/pypi/simple/
# root@0defa034f2a4:/workspace# pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
# root@170cd98e309e:/share/yk_repo/Megatron-LM/tag_23.06/apex# pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./


!!!!!!!!!!!版本不匹配，废弃！！！！
